from fpdf import FPDF
from app.models import AnalysisResult
import os

# ==========================================
# Report Generator Agent Helper
# ==========================================
# This module acts as the core logic for the Report Generator Agent.
# In an enterprise setting, this would integrate with BI tools like Tableau or PowerBI,
# or use a high-fidelity PDF engine like ReportLab with corporate templates.
# Here, we simulate this using FPDF for a lightweight, hackathon-friendly solution.

class PDFReport(FPDF):
    def header(self):
        # Simulating Corporate Branding
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Pharma Strategy Analysis Report', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'CONFIDENTIAL - INTERNAL USE ONLY', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Agentic AI Platform', 0, 0, 'C')

    def clean_text(self, text):
        """Sanitizes text to be compatible with latin-1 encoding."""
        if not isinstance(text, str):
            return str(text)
        replacements = {
            '\u2013': '-',  # en dash
            '\u2014': '-',  # em dash
            '\u2018': "'",  # left single quote
            '\u2019': "'",  # right single quote
            '\u201c': '"',  # left double quote
            '\u201d': '"',  # right double quote
            '\u2026': '...', # ellipsis
        }
        for char, replacement in replacements.items():
            text = text.replace(char, replacement)
        return text.encode('latin-1', 'replace').decode('latin-1')

def generate_pdf_report(data: AnalysisResult, filename: str = "report.pdf") -> str:
    """
    Generates a structured PDF report from the analysis data.
    Simulates the output of a professional strategy consulting report.
    """
    pdf = PDFReport()
    pdf.add_page()
    
    # 1. Executive Summary
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, pdf.clean_text('1. Executive Summary'), 0, 1)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 8, pdf.clean_text(f"Thesis: {data.summary.thesis}"))
    pdf.ln(5)
    
    # Key Metrics Table (Simulated)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(40, 10, pdf.clean_text('Metric'), 1)
    pdf.cell(100, 10, pdf.clean_text('Assessment'), 1)
    pdf.ln()
    
    pdf.set_font('Arial', '', 10)
    pdf.cell(40, 10, pdf.clean_text('Confidence'), 1)
    pdf.cell(100, 10, pdf.clean_text(data.summary.confidence), 1)
    pdf.ln()
    pdf.cell(40, 10, pdf.clean_text('Commercial Potential'), 1)
    pdf.cell(100, 10, pdf.clean_text(data.recommendation.commercialPotential.split('—')[0].strip()), 1) # Shorten for table
    pdf.ln(10)

    # 2. Market Opportunity
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, pdf.clean_text('2. Market Opportunity'), 0, 1)
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 8, pdf.clean_text(f"Therapy Area: {data.market.therapy}"), 0, 1)
    pdf.cell(0, 8, pdf.clean_text(f"Target Geography: {data.market.country}"), 0, 1)
    pdf.cell(0, 8, pdf.clean_text(f"Market Size: ${data.market.marketSize:,}"), 0, 1)
    pdf.cell(0, 8, pdf.clean_text(f"CAGR (3-Year): {data.market.cagr}%"), 0, 1)
    
    if data.exim:
        pdf.ln(5)
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(0, 8, pdf.clean_text("Supply Chain & Trade Risks (EXIM Data):"), 0, 1)
        pdf.set_font('Arial', '', 11)
        pdf.cell(0, 8, pdf.clean_text(f"- Export Volume: {data.exim.exportVolume:,} units"), 0, 1)
        pdf.cell(0, 8, pdf.clean_text(f"- Dependency Risk: {data.exim.dependencyRisk}"), 0, 1)
    pdf.ln(5)

    # 3. Clinical Landscape
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, pdf.clean_text(f'3. Clinical Landscape ({len(data.trials)} Active Trials)'), 0, 1)
    
    # Trials Table
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(30, 8, pdf.clean_text('NCT ID'), 1)
    pdf.cell(90, 8, pdf.clean_text('Title'), 1)
    pdf.cell(30, 8, pdf.clean_text('Phase'), 1)
    pdf.cell(30, 8, pdf.clean_text('Status'), 1)
    pdf.ln()
    
    pdf.set_font('Arial', '', 8)
    for trial in data.trials:
        pdf.cell(30, 8, pdf.clean_text(trial.nct), 1)
        # Truncate title if too long
        title = (trial.title[:45] + '...') if len(trial.title) > 45 else trial.title
        pdf.cell(90, 8, pdf.clean_text(title), 1)
        pdf.cell(30, 8, pdf.clean_text(trial.phase), 1)
        pdf.cell(30, 8, pdf.clean_text(trial.status), 1)
        pdf.ln()
    pdf.ln(5)

    # 4. Patent Intelligence
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, pdf.clean_text(f'4. Patent Intelligence ({len(data.patents)} Key Patents)'), 0, 1)
    pdf.set_font('Arial', '', 11)
    for patent in data.patents:
        pdf.multi_cell(0, 8, pdf.clean_text(f"- {patent.patentId}: {patent.title} (Expires: {patent.expiryDate}) [FTO: {patent.ftoFlag}]"))
    pdf.ln(5)

    # 5. Strategic Recommendation
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, pdf.clean_text('5. Strategic Recommendation'), 0, 1)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 8, pdf.clean_text(f"Recommended Path: {data.recommendation.path}"))
    pdf.multi_cell(0, 8, pdf.clean_text(f"Timeline: {data.recommendation.timeline}"))
    pdf.ln(5)
    
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 8, pdf.clean_text("Next Steps:"), 0, 1)
    pdf.set_font('Arial', '', 11)
    for step in data.recommendation.nextSteps:
        pdf.cell(0, 8, pdf.clean_text(f"- {step}"), 0, 1)

    # Output File
    output_path = os.path.join("app", "static", filename)
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return output_path
